/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /buildstream/freedesktop-sdk/base/perl.bst/miniperl ../bin/enc2xs -Q -o ji_04_t.c -f ji_04_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t jis0212_raw_encoding;
